### ISSUE TITLE
PDF Embed Issues

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/gdrive#25]
Although Gdoc native files seems to embed fine, when attempting to embed a PDF from Google Drive, the document appears in the editor, but not within the content of the blog on the front end. See video: 

https://drive.google.com/a/hwdsb.on.ca/file/d/1FVhl4ukv24Y6atMOfcAkX91QoRqlo-xi/view?usp=drivesdk

**Comment by r-a-y** [comment]
Confirmed.

It's an issue with the Google Docs Shortcode plugin.  I've just pushed up a fix on production.
Can you give it a test?

**Comment by mrjarbenne** [comment]
Previously nothing was rendering. Now I'm seeing the black frame of the iframe, but the PDF still doesn't seem to be rendering in the front end (still works in the back, and works in the classic editor).

https://sandbox.commons.hwdsb.on.ca/2019/09/pdf-test/

![2019-09-02_18-11-39 (1)](https://user-images.githubusercontent.com/480667/64134592-385a7780-cdad-11e9-9401-3a49d064d922.gif)

**Comment by r-a-y** [comment]
I think I've fixed things.  Link was previously using HTTP.  I've now defaulted it to HTTPS, so it should work now.

**Comment by mrjarbenne** [comment]
Fixed. Cheers!
